### ISSUE TITLE
Gatsby (running locally) crashes when an images is swapped in Sanity

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers.cloudflare.com#65]
I noticed this just now as I was changing some project images.

If in Sanity I upload a new image for a project and then hit publish, I see this in my terminal:

```
/Users/[redacted]/.nvm/versions/node/v8.12.0/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'write' of null
    at Zlib.callback (zlib.js:499:33)
```

**Comment by signalnerve** [comment]
woah, very interesting. think we should keep this in the milestone for a bit of investigation, if it doesn't feel doable i'll update here and punt for later

**Comment by signalnerve** [comment]
@adamschwartz just tried to recreate this, i was able to change the image and see it refresh w/o errors or crashing. maybe when you have some time next week you could try this again on your machine and see what happens? fwiw, i just updated a few plugins in the sanity studio env this morning so maybe it's fixed with that?

**Comment by signalnerve** [comment]
closing as i think this is fixed!
